"""
Generate pinyin-map.js — a compact simplified-Chinese -> pinyin-initial map.

Scope: GB2312 level-1 hanzi (3755 chars, ~99.7% of everyday text) to keep the
generated file small. Run with:

    python scripts/generate-pinyin-map.py

Requires: pip install pypinyin
"""

import os
from pypinyin import pinyin, Style

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "pinyin-map.js")


def first_letter(ch):
    """Return the pinyin initial (a-z) for a hanzi, or None."""
    try:
        result = pinyin(ch, style=Style.FIRST_LETTER, errors="ignore")
    except Exception:
        return None
    if not result or not result[0]:
        return None
    letter = result[0][0]
    if letter and len(letter) == 1 and "a" <= letter <= "z":
        return letter
    return None


def main():
    groups = {chr(c): "" for c in range(ord("a"), ord("z") + 1)}

    for code in range(0x4E00, 0x9FA6):
        ch = chr(code)
        # Keep only GB2312 level-1 (most common) hanzi
        try:
            raw = ch.encode("gb2312")
        except UnicodeEncodeError:
            continue
        if len(raw) != 2 or not (0xB0 <= raw[0] <= 0xD7):
            continue

        letter = first_letter(ch)
        if letter:
            groups[letter] += ch

    total = sum(len(v) for v in groups.values())
    if total < 1000:
        raise SystemExit("Too few characters collected (%d) — is pypinyin installed?" % total)

    lines = [
        "/**",
        " * Simplified Chinese -> pinyin initial letter map.",
        " * Generated by scripts/generate-pinyin-map.py — do not edit by hand.",
        " *",
        " * Scope: GB2312 level-1 hanzi (%d chars), enough for %s style" % (total, "gswa -> 公司文案"),
        " * initial-letter search. Regenerate after changing the generator.",
        " */",
        "(function () {",
        "  if (typeof window === 'undefined') return;",
        "  if (window.PVPinyinMap) return; // idempotency guard",
        "",
        "  const GROUPS = {",
    ]
    for letter in sorted(groups):
        lines.append("    %s: '%s'," % (letter, groups[letter]))
    lines += [
        "  };",
        "",
        "  const map = Object.create(null);",
        "  for (const letter in GROUPS) {",
        "    const chars = GROUPS[letter];",
        "    for (let i = 0; i < chars.length; i++) map[chars[i]] = letter;",
        "  }",
        "",
        "  window.PVPinyinMap = map;",
        "})();",
        "",
    ]

    path = os.path.normpath(OUT)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    print("written:", path)
    print("chars:", total)
    print("bytes:", os.path.getsize(path))


if __name__ == "__main__":
    main()
